'use client';
import {useEffect,useMemo,useState} from 'react';
import {BarChart3,BookOpen,BrainCircuit,CheckCircle2,ChevronDown,ChevronRight,ClipboardList,Database,FileText,Globe2,LayoutDashboard,Menu,Plus,Search,Settings,ShieldCheck,SlidersHorizontal,TrendingUp,X,Bell,UserRound,LogOut,ArrowUpRight,Sun,Moon,LockKeyhole,Mail,Save,UserPlus,Eye,EyeOff} from 'lucide-react';

type Job={id:string;title:string;status:string;progress:number;sources:number};
type DatasetOverview={requests:number;sources:number;evidence:number;validated_evidence:number;completed:number;running:number;pending:number;needs_review:number;avg_confidence:number;top_topics:any[];top_entities:any[];evidence_by_year:any[];market_metrics:any[];demo?:boolean};
const API = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8000';
const initialJobs:Job[]=[{id:'job-104',title:'Global EV Market Trends 2025',status:'Completed',progress:100,sources:12},{id:'job-103',title:'AI in Healthcare Industry Analysis',status:'Running',progress:45,sources:8},{id:'job-102',title:'Competitor Landscape',status:'Pending',progress:0,sources:0}];
const agents=[['Planner Agent','Creates research plan and strategy','Working'],['Browser Agent','Navigates web and collects sources','Active'],['Extractor Agent','Extracts structured data from sources','Active'],['Validator Agent','Verifies facts and cross-checks evidence','Active'],['Report Writer Agent','Creates final report with citations','Waiting']];
const stages=['intake','planning','browsing','extraction','validation','aggregation','report_generation','review'];
const labels=['Intake','Planning','Browsing','Extraction','Validation','Aggregation','Report Generation','Review'];

type Account={userId:string;name:string;email:string;role:string;status?:string;createdAt?:string;lastLogin?:string};
const SESSION_KEY='mcx_server_session_v2';
const THEME_KEY='mcx_theme_v1';

function apiHeaders(token?:string){
  return token ? {'Authorization':`Bearer ${token}`} : {};
}
function AuthScreen({onLogin}:{onLogin:(a:Account)=>void}){
 const [mode,setMode]=useState<'login'|'create'>('login'); const [userId,setUserId]=useState(''); const [password,setPassword]=useState(''); const [name,setName]=useState(''); const [email,setEmail]=useState(''); const [show,setShow]=useState(false); const [error,setError]=useState(''); const [busy,setBusy]=useState(false);
 const submit=async(e:any)=>{e.preventDefault();setError('');setBusy(true);
  try{
   const endpoint=mode==='create'?'/api/auth/register':'/api/auth/login';
   const body=mode==='create'?{user_id:userId.trim(),full_name:name.trim(),email:email.trim(),password}:{user_id:userId.trim(),password};
   const r=await fetch(`${API}${endpoint}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});
   const j=await r.json().catch(()=>({}));
   if(!r.ok)throw new Error(j.detail||'Authentication failed.');
   if(mode==='create'){
     setMode('login'); setError('Account created successfully. Sign in on any device using the same User ID and password.'); setPassword('');
     return;
   }
   localStorage.setItem(SESSION_KEY,j.token); onLogin(j.user);
  }catch(err:any){setError(err?.message||'Authentication failed.')}finally{setBusy(false)}
 };
 return <div className="auth-shell"><div className="auth-visual"><div className="auth-brand"><span>✣</span><div>McKinsey<br/><em>& Company</em></div></div><div className="auth-message"><div className="eyebrow light">AI market research & strategy</div><h1>Research at the speed of strategy.</h1><p>Turn complex business questions into traceable evidence, market signals and review-ready strategy briefs.</p><div className="auth-points"><span>01 · Evidence-led research</span><span>02 · Agent workflow control</span><span>03 · Strategy-ready synthesis</span></div></div></div><div className="auth-card"><div className="auth-head"><div><div className="eyebrow">Secure workspace access</div><h2>{mode==='login'?'Welcome back':'Create your account'}</h2><p>{mode==='login'?'Sign in to continue to your research workspace.':'Create a centralized research workspace account.'}</p></div></div><form onSubmit={submit}>{mode==='create'&&<><label>Full name<input value={name} onChange={e=>setName(e.target.value)} placeholder="Sarah Johnson" required/></label><label>Email address<div className="input-icon"><Mail size={16}/><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@company.com" required/></div></label></>}<label>User ID<input value={userId} onChange={e=>setUserId(e.target.value)} placeholder="sarah.johnson" autoComplete="username" required/></label><label>Password<div className="input-icon"><LockKeyhole size={16}/><input type={show?'text':'password'} value={password} onChange={e=>setPassword(e.target.value)} placeholder="••••••••" autoComplete={mode==='login'?'current-password':'new-password'} required/><button type="button" className="password-toggle" onClick={()=>setShow(!show)}>{show?<EyeOff size={16}/>:<Eye size={16}/>}</button></div></label>{error&&<div className={`auth-error ${mode==='login'&&error.includes('created successfully')?'auth-success':''}`}>{error}</div>}<button className="auth-submit" type="submit" disabled={busy}>{busy?'Please wait…':mode==='login'?'Sign in':'Create account'} <ArrowUpRight size={17}/></button></form><div className="auth-switch">{mode==='login'?<>New to the workspace? <button onClick={()=>{setMode('create');setError('')}}>Create new account <UserPlus size={14}/></button></>:<>Already have an account? <button onClick={()=>{setMode('login');setError('')}}>Sign in</button></>}</div><small className="auth-note">Accounts are stored centrally in Supabase through the backend. You can create an account on one device and sign in from another.</small></div></div>
}

export default function Home(){
 const [account,setAccount]=useState<Account|null>(null); const [ready,setReady]=useState(false); const [theme,setTheme]=useState<'light'|'dark'>('light');
 const [view,setView]=useState('Dashboard'); const [jobs,setJobs]=useState(initialJobs); const [query,setQuery]=useState(''); const [activeJob,setActiveJob]=useState<any>(null); const [running,setRunning]=useState(false); const [searchOpen,setSearchOpen]=useState(false); const [profileOpen,setProfileOpen]=useState(false); const [mobileNav,setMobileNav]=useState(false); const [data,setData]=useState<DatasetOverview|null>(null); const [dataLoading,setDataLoading]=useState(true); const [providerStatus,setProviderStatus]=useState<any>(null);
 useEffect(()=>{(async()=>{try{const token=localStorage.getItem(SESSION_KEY);if(token){const r=await fetch(`${API}/api/auth/me`,{headers:apiHeaders(token)});if(r.ok){const j=await r.json();setAccount(j.user)}else localStorage.removeItem(SESSION_KEY)}const t=(localStorage.getItem(THEME_KEY)||'light') as 'light'|'dark';setTheme(t);document.documentElement.dataset.theme=t;}catch(e){console.error('Auth session check failed',e)}finally{setReady(true)}})()},[]);
 const changeTheme=(t:'light'|'dark')=>{setTheme(t);localStorage.setItem(THEME_KEY,t);document.documentElement.dataset.theme=t};
 const signOut=async()=>{const token=localStorage.getItem(SESSION_KEY);try{if(token)await fetch(`${API}/api/auth/logout`,{method:'POST',headers:apiHeaders(token)})}catch{}localStorage.removeItem(SESSION_KEY);setAccount(null);setProfileOpen(false)};
 const stats=useMemo(()=>({total:data?.requests??0,completed:data?.completed??0,progress:data?.running??0,failed:data?.needs_review??0}),[data]);
 const loadData=async()=>{try{setDataLoading(true);const r=await fetch(`${API}/api/data/overview`);if(!r.ok){const body=await r.text();throw new Error(body||`Dataset request failed (${r.status})`)}setData(await r.json())}catch(e:any){setData(null);console.error('Dataset load failed:',e);setDataLoading(false);return}finally{setDataLoading(false)}};
 useEffect(()=>{if(account){loadData();fetch(`${API}/api/providers/status`).then(r=>r.ok?r.json():null).then(setProviderStatus).catch(()=>{})}},[account]);
 if(!ready)return <div className="auth-loading">Loading workspace…</div>; if(!account)return <AuthScreen onLogin={setAccount}/>;
 const start=async(form?:any)=>{const q=(form?.query??query).trim();if(!q||running)return;setRunning(true);setView('Workflow');try{const payload={query:q,market:form?.market??'',geography:form?.geography??'',competitors:form?.competitors??[],timeframe:form?.timeframe??'',report_depth:form?.report_depth??'standard',output_format:form?.output_format??'internal review'};const r=await fetch(`${API}/api/research-run`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!r.ok)throw new Error(await r.text());const data=await r.json();setActiveJob(data);setJobs(j=>[{id:data.id,title:q,status:'Completed',progress:100,sources:data.sources?.length||0},...j]);}catch(e:any){setActiveJob({error:e?.message||'Research run failed',stage_status:{}})}finally{setRunning(false)}};
 const nav=[['Dashboard',LayoutDashboard],['New Research',Plus],['My Research Jobs',ClipboardList],['Sources & Library',Globe2],['Knowledge Base',BookOpen],['Reports',FileText],['Operations',BarChart3],['Settings',Settings]] as const;
 return <div className="app-shell">
  <aside className={`sidebar ${mobileNav?'mobile-open':''}`}><div className="brand"><span className="brand-mark">✣</span><span>McKinsey<br/><em>& Company</em></span></div><button className="mobile-close" onClick={()=>setMobileNav(false)}><X size={20}/></button><nav>{nav.map(([n,I])=><button key={n} onClick={()=>{setView(n);setMobileNav(false)}} className={`nav-item ${view===n?'active':''}`}><I size={18}/><span>{n}</span></button>)}</nav><div className="usage"><div className="usage-title">Credits & Usage</div><div className="usage-row"><span>1,250 / 2,000</span><span>62%</span></div><div className="usage-track"><div/></div><small>Research capacity this cycle</small></div></aside>
  <main className="main-area">
   <header className="topbar"><button className="mobile-menu" onClick={()=>setMobileNav(true)}><Menu size={21}/></button><div className={`global-search ${searchOpen?'focused':''}`}><Search size={19}/><input value={query} onFocus={()=>setSearchOpen(true)} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&query.trim()){setView('New Research');setSearchOpen(false)}}} placeholder="Search research jobs, topics, or sources..."/><kbd>⌘ K</kbd>{searchOpen&&<button className="clear-search" onClick={()=>{setQuery('');setSearchOpen(false)}}><X size={16}/></button>}</div><div className="top-actions"><button className="icon-btn notification"><Bell size={19}/><i/></button><div className="profile-wrap"><button className="profile" onClick={()=>setProfileOpen(!profileOpen)}><span className="avatar">{account.name.split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase()}</span><span className="profile-copy"><strong>{account.name}</strong><small>{account.role}</small></span><ChevronDown size={16}/></button>{profileOpen&&<div className="profile-menu"><div className="menu-user"><span className="avatar">{account.name.split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase()}</span><div><strong>{account.name}</strong><small>{account.role}</small></div></div><button onClick={()=>setView('Profile')}><UserRound size={17}/> Profile</button><button onClick={()=>setView('Settings')}><Settings size={17}/> Settings</button><hr/><button onClick={signOut}><LogOut size={17}/> Sign out</button></div>}</div></div></header>
   {searchOpen&&<div className="search-overlay"><div className="search-panel"><div className="panel-label">Quick actions</div>{[['Create new research job',Plus],['View recent research jobs',ClipboardList],['Browse sources',FileText],['Search knowledge base',BookOpen]].map(([x,I]:any)=><button key={x} onClick={()=>{setView(x.startsWith('Create')?'New Research':x.startsWith('View')?'My Research Jobs':x.startsWith('Browse')?'Sources & Library':'Knowledge Base');setSearchOpen(false)}}><span className="quick-icon"><I size={17}/></span>{x}<ChevronRight size={16}/></button>)}<div className="panel-label recent">Recent searches</div>{['online food-delivery market India','EV market analysis','consumer behavior trends','competitive landscape'].map(x=><button className="recent-search" key={x} onClick={()=>{setQuery(x);setSearchOpen(false)}}><Search size={16}/>{x}<ChevronRight size={15}/></button>)}</div></div>}
   <div className="content">{view==='New Research'?<Intake query={query} setQuery={setQuery} start={start} running={running}/>:view==='Workflow'?<WorkflowView job={activeJob} running={running}/>:view==='Reports'?<ReportView job={activeJob} data={data}/>:view==='My Research Jobs'?<JobsView jobs={jobs} setView={setView} setActiveJob={setActiveJob}/>:view==='Sources & Library'?<EvidenceView/>:view==='Knowledge Base'?<MemoryView setView={setView}/>:view==='Operations'?<OpsView/>:view==='Profile'?<ProfileView account={account}/>:view==='Settings'?<SettingsView account={account} setAccount={setAccount} theme={theme} changeTheme={changeTheme} signOut={signOut}/>:<Dashboard setView={setView} query={query} providerStatus={providerStatus} setQuery={setQuery} start={start} jobs={jobs} stats={stats} data={data} loading={dataLoading}/>}</div>
  </main>
 </div>
}

function Dashboard(p:any){const d=p.data;return <div className="dashboard"><div className="page-head"><div><div className="eyebrow">Strategy intelligence workspace</div><h1>Research at the speed of strategy.</h1><p>Turn complex questions into traceable evidence, market signals and review-ready strategy briefs.</p></div><button className="outline-btn" onClick={()=>p.setView('New Research')}><Plus size={17}/> New research</button></div>
 <div className="dataset-live-badge">{d?.demo?"Demo dataset":"Supabase PostgreSQL + pgvector"}{p.providerStatus?.recommended_mode === "knowledge_base" ? " · Knowledge Base mode" : " · Provider failover active"}</div><section className="hero-query"><div><div className="eyebrow light">AI-powered market research</div><h2>What should we research next?</h2><p>Start with a business question. The engine plans, browses, extracts, validates and synthesizes the evidence.</p></div><div className="query-launch"><Search size={19}/><input value={p.query} onChange={e=>p.setQuery(e.target.value)} onKeyDown={(e:any)=>e.key==='Enter'&&p.start()} placeholder="e.g. Assess market entry opportunity in..."/><button onClick={p.start}>Start research <ArrowUpRight size={17}/></button></div></section>
 <div className="kpi-grid">{[['Research jobs',p.stats.total,'Dataset requests','My Research Jobs'],['Completed briefs',p.stats.completed,'Completed demo requests','Reports'],['Active research',p.stats.progress,'Currently running','Workflow'],['Needs review',p.stats.failed,'Evidence quality queue','Sources & Library']].map((x:any,i:number)=><button className="metric-card metric-card-button" key={x[0]} onClick={()=>p.setView(x[3])} aria-label={`Open ${x[0]}`}><div className="metric-top"><span>{x[0]}</span><span className="metric-icon">{i===0?<ClipboardList size={16}/>:i===1?<CheckCircle2 size={16}/>:i===2?<TrendingUp size={16}/>:<ShieldCheck size={16}/>}</span></div><strong>{p.loading?'…':x[1].toLocaleString()}</strong><small>{x[2]}</small><MiniLine variant={i}/></button>)}</div>
 <div className="data-chart-grid"><DynamicLine title="Evidence volume by year" data={d?.evidence_by_year||[]} xKey="year" yKey="value"/><DynamicBars title="Top research themes" data={(d?.top_topics||[]).slice(0,7)} xKey="label" yKey="value"/></div>
 <div className="insight-grid"><InsightCard title="Market signals" subtitle="Emerging themes across selected sources" value={d?`${Math.round(d.avg_confidence)}%`:'—'} label="average confidence" variant="line" actionLabel="View signals" onExplore={()=>p.setView('Sources & Library')}/><InsightCard title="Supplier / competitor structure" subtitle="Observed movements in tracked companies" value={(d?.top_entities?.length||0).toLocaleString()} label="tracked entities" variant="bars" actionLabel="View competitors" onExplore={()=>p.setView('Knowledge Base')}/><InsightCard title="Risk & exposure" subtitle="Validated dependency and geography flags" value={(d?.needs_review||0).toLocaleString()} label="items for review" variant="donut" actionLabel="Review risks" onExplore={()=>p.setView('Sources & Library')}/><InsightCard title="Pricing & demand" subtitle="Changes in price, volume and customer behavior" value={(d?.evidence||0).toLocaleString()} label="evidence records" variant="area" actionLabel="View demand" onExplore={()=>p.setView('Sources & Library')}/><InsightCard title="Working capital" subtitle="Operational themes and value levers" value={(d?.validated_evidence||0).toLocaleString()} label="validated records" variant="donut2" actionLabel="Review evidence" onExplore={()=>p.setView('Sources & Library')}/><InsightCard title="Value leakage" subtitle="Where research points to strategic gaps" value={(d?.top_topics||[]).filter((x:any)=>x.label==='value leakage').reduce((a:number,x:any)=>a+x.value,0).toLocaleString()} label="theme records" variant="bars2" actionLabel="Explore themes" onExplore={()=>p.setView('Knowledge Base')}/></div>
 <div className="lower-grid"><div className="dark-panel"><div className="panel-head"><div><div className="eyebrow light">Live workflow</div><h3>Research control tower</h3></div><button onClick={()=>p.setView('Workflow')}>Open monitor <ChevronRight size={16}/></button></div><div className="workflow-strip">{labels.map((x,i)=><div key={x} className="flow-node"><span>{i+1}</span><b>{x}</b>{i<labels.length-1&&<i/>}</div>)}</div></div><div className="recent-card"><div className="panel-head"><div><div className="eyebrow">Activity</div><h3>Recent research jobs</h3></div><button onClick={()=>p.setView('My Research Jobs')}>View all <ChevronRight size={16}/></button></div>{p.jobs.slice(0,3).map((j:Job)=><div className="job-row" key={j.id}><div className="job-badge"><FileText size={16}/></div><div><strong>{j.title}</strong><small>Web research · {j.sources} sources</small></div><span className={`status ${j.status.toLowerCase()}`}>{j.status}</span></div>)}</div></div>
 <div className="stack-strip"><div><span className="eyebrow">Built for governed research</span><h3>Planner · Browser · Extraction · Validation · Memory · Report</h3></div><div className="stack-items"><span>Next.js</span><span>FastAPI</span><span>Gemini</span><span>Firecrawl</span><span>Chroma / Qdrant</span><span>PostgreSQL</span></div></div></div>}
function DynamicLine({title,data,xKey,yKey}:{title:string;data:any[];xKey:string;yKey:string}){const vals=data.map(x=>Number(x[yKey])||0);const max=Math.max(...vals,1);const pts=vals.map((v,i)=>`${12+i*(176/Math.max(vals.length-1,1))},${54-(v/max)*42}`).join(' ');return <section className="data-chart-card"><div className="chart-card-head"><div><div className="eyebrow">Dynamic dataset</div><h3>{title}</h3></div><span>{data.length} periods</span></div>{data.length?<svg viewBox="0 0 200 72" className="dynamic-svg"><polyline points={pts} fill="none" className="chart-line"/>{vals.map((v,i)=><circle key={i} cx={12+i*(176/Math.max(vals.length-1,1))} cy={54-(v/max)*42} r="2.8" className="chart-point"/>)}{data.map((x,i)=><text key={i} x={12+i*(176/Math.max(data.length-1,1))} y="69" textAnchor="middle" className="chart-label">{x[xKey]}</text>)}</svg>:<div className="empty-state">Dataset is loading…</div>}</section>}
function DynamicBars({title,data,xKey,yKey}:{title:string;data:any[];xKey:string;yKey:string}){const max=Math.max(...data.map(x=>Number(x[yKey])||0),1);return <section className="data-chart-card"><div className="chart-card-head"><div><div className="eyebrow">Dynamic dataset</div><h3>{title}</h3></div><span>Top {data.length}</span></div><div className="dynamic-bars">{data.map((x,i)=><div key={i} className="dynamic-bar-row"><span title={x[xKey]}>{x[xKey]}</span><div><i style={{width:`${Math.max(4,(Number(x[yKey])/max)*100)}%`}}/></div><b>{Number(x[yKey]).toLocaleString()}</b></div>)}</div></section>}
function MiniLine({variant}:{variant:number}){return <svg className="mini-chart" viewBox="0 0 120 30" preserveAspectRatio="none"><polyline points={variant===0?'0,25 18,20 35,23 55,12 75,16 95,6 120,9':variant===1?'0,20 20,17 40,20 60,10 80,14 100,7 120,10':variant===2?'0,15 20,18 40,11 60,17 80,9 100,12 120,5':'0,23 20,18 40,20 60,13 80,14 100,8 120,6'} fill="none" stroke="currentColor" strokeWidth="2"/></svg>}
function InsightCard({title,subtitle,value,label,variant,actionLabel='Explore',onExplore}:{title:string;subtitle:string;value:string;label:string;variant:string;actionLabel?:string;onExplore:()=>void}){return <article className="insight-card interactive" tabIndex={0} role="button" aria-label={`${title}: ${actionLabel}`} onClick={onExplore} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onExplore()}}}><div className="insight-head"><div><h3>{title}</h3><p>{subtitle}</p></div><button type="button" aria-label={`Open ${title} controls`} onClick={e=>{e.stopPropagation();onExplore()}}><SlidersHorizontal size={15}/></button></div><div className="insight-body"><div><strong>{value}</strong><small>{label}</small></div><Chart variant={variant}/></div><button type="button" className="explore" onClick={e=>{e.stopPropagation();onExplore()}}>{actionLabel} <ArrowUpRight size={14}/></button></article>}
function Chart({variant}:{variant:string}){if(variant==='donut'||variant==='donut2')return <div className={`donut ${variant}`}><span>72%</span></div>;if(variant==='bars'||variant==='bars2')return <div className="bars">{[18,30,24,42,31,48].map((h,i)=><i key={i} style={{height:`${h}px`}}/>)}</div>;return <svg className="chart" viewBox="0 0 180 60" preserveAspectRatio="none"><path d={variant==='area'?'M0 48 L28 44 L55 48 L84 29 L112 35 L145 18 L180 23 L180 60 L0 60 Z':'M0 50 L25 45 L48 48 L72 32 L98 38 L124 16 L150 22 L180 8'} fill="currentColor" opacity=".12"/><polyline points={variant==='area'?'0,48 28,44 55,48 84,29 112,35 145,18 180,23':'0,50 25,45 48,48 72,32 98,38 124,16 150,22 180,8'} fill="none" stroke="currentColor" strokeWidth="2.5"/></svg>}
function Intake({query,setQuery,start,running}:any){const [market,setMarket]=useState('');const [geography,setGeography]=useState('');const [competitors,setCompetitors]=useState('');const [timeframe,setTimeframe]=useState('');const [depth,setDepth]=useState('Detailed');const [output,setOutput]=useState('Internal review');return <div className="intake-page"><div className="page-head"><div><div className="eyebrow">Research intake console</div><h1>Frame the question before the agents run.</h1><p>Define scope, market context, competitors, timeframe and expected output.</p></div></div><div className="intake-layout"><div className="intake-card"><label>Research question<textarea value={query} onChange={e=>setQuery(e.target.value)} placeholder="e.g. Assess the market-entry opportunity for..."/></label><div className="form-grid"><Field label="Target market / sector" value={market} setValue={setMarket} placeholder="Online Food Delivery"/><Field label="Geography" value={geography} setValue={setGeography} placeholder="India"/><Field label="Competitors" value={competitors} setValue={setCompetitors} placeholder="Zomato, Swiggy"/><Field label="Timeframe" value={timeframe} setValue={setTimeframe} placeholder="2024–2026"/><label>Report depth<select value={depth} onChange={e=>setDepth(e.target.value)}><option>Standard</option><option>Detailed</option><option>Deep dive</option></select></label><label>Output<select value={output} onChange={e=>setOutput(e.target.value)}><option>Internal review</option><option>Proposal</option><option>Workshop</option></select></label></div><div className="intake-footer"><span><ShieldCheck size={16}/> Sources remain traceable through validation.</span><button disabled={running} onClick={()=>start({query,market,geography,competitors:competitors.split(',').map((x:string)=>x.trim()).filter(Boolean),timeframe,report_depth:depth,output_format:output})}>{running?'Running workflow…':'Create Research Job'} <ArrowUpRight size={17}/></button></div></div><WorkflowPreview/></div></div>}
function Field({label,value,setValue,placeholder}:any){return <label>{label}<input value={value} onChange={e=>setValue(e.target.value)} placeholder={placeholder}/></label>}
function WorkflowPreview(){return <aside className="workflow-preview"><div className="eyebrow">Research workflow</div><h2>From question to actionable insight.</h2>{labels.map((x,i)=><div className="preview-step" key={x}><span>{i+1}</span><div><b>{x}</b><small>{i===0?'Scope and context':i===1?'Research tasks':'Evidence and synthesis'}</small></div></div>)}<div className="preview-note"><ShieldCheck size={17}/><span>Every material claim should remain connected to a source and validation signal.</span></div></aside>}
function WorkflowView({job,running}:any){const status=(s:string)=>job?.stage_status?.[s]||(running?'waiting':'waiting');const done=(s:string)=>['complete','ready'].includes(status(s));return <div><div className="page-head"><div><div className="eyebrow">Agent workflow monitor</div><h1>Research control tower</h1><p>Inspectable research job lifecycle and evidence traceability.</p></div></div><div className="workflow-monitor">{stages.map((s,i)=>{const st=status(s);return <div className="monitor-step" key={s}><div className={`step-dot ${done(s)?'done':st==='failed'?'failed':st==='running'?'run':''}`}>{done(s)?<CheckCircle2 size={17}/>:i+1}</div><div className="step-copy"><b>{labels[i]}</b><small>{done(s)?'Complete':st==='running'?'Running…':st==='failed'?'Failed':running?'Waiting for upstream workflow step':'Not started'}</small></div>{done(s)&&<span className="status completed">Done</span>}{st==='running'&&<span className="status running">Running</span>}{st==='failed'&&<span className="status failed">Failed</span>}</div>})}</div>{job?.error&&<div className="error-box">{job.error}</div>}{job?.report&&<div className="report-result"><div className="eyebrow">Generated research brief</div><h2>{job.report.title||'Report ready'}</h2><p>{job.report.evidence_count} validated evidence records · human review required before client use.</p><h3>Executive summary</h3><p className="report-copy">{job.report.executive_summary}</p>{job.report.exhibits?.length>0&&<div className="workflow-exhibit-note"><BarChart3 size={16}/> {job.report.exhibits.length} quantitative exhibit{job.report.exhibits.length===1?'':'s'} generated from validated evidence.</div>}{job.report.key_findings?.length>0&&<><h3>Key findings</h3><ul>{job.report.key_findings.map((x:string,i:number)=><li key={i}>{x}</li>)}</ul></>}{job.report.citations?.length>0&&<><h3>Evidence appendix</h3>{job.report.citations.map((x:string,i:number)=><a className="source-link" href={x} target="_blank" rel="noreferrer" key={i}>{x}</a>)}</>}</div>}</div>}
function JobsView({jobs,setView,setActiveJob}:{jobs:Job[];setView:(v:string)=>void;setActiveJob:(j:any)=>void}){return <div><div className="page-head"><div><div className="eyebrow">Research portfolio</div><h1>Every research job, in one place.</h1><p>Open a job, monitor its workflow, or move directly to the resulting brief.</p></div><button className="outline-btn" onClick={()=>setView('New Research')}><Plus size={17}/> New research</button></div><div className="jobs-table"><div className="jobs-table-head"><span>Research job</span><span>Status</span><span>Progress</span><span>Sources</span><span></span></div>{jobs.map(j=><div className="jobs-table-row" key={j.id}><div><strong>{j.title}</strong><small>{j.id} · Web research</small></div><span className={`status ${j.status.toLowerCase()}`}>{j.status}</span><div className="job-progress"><div><i style={{width:`${j.progress}%`}}/></div><small>{j.progress}%</small></div><span>{j.sources}</span><button className="row-action" onClick={()=>{setActiveJob({title:j.title,stage_status:j.progress===100?Object.fromEntries(stages.map(s=>[s,'complete'])):{},report:null});setView(j.status==='Completed'?'Reports':'Workflow')}}>Open <ArrowUpRight size={14}/></button></div>)}</div></div>}

function EvidenceView(){
 const [items,setItems]=useState<any[]>([]);
 const [filters,setFilters]=useState<any>({markets:['All'],topics:['All'],statuses:['All']});
 const [market,setMarket]=useState('All'); const [topic,setTopic]=useState('All'); const [validation,setValidation]=useState('All');
 const [search,setSearch]=useState(''); const [page,setPage]=useState(1); const [meta,setMeta]=useState<any>(null); const [message,setMessage]=useState('');
 const load=async()=>{try{const q=new URLSearchParams({page:String(page),page_size:'12',market,topic,validation,search});const [a,b]=await Promise.all([fetch(`${API}/api/data/evidence?${q}`),fetch(`${API}/api/data/filters`)]);if(a.ok){const j=await a.json();setItems(j.items);setMeta(j)}if(b.ok)setFilters(await b.json())}catch{}};
 useEffect(()=>{load()},[page,market,topic,validation,search]);
 const act=async(i:number,a:string)=>{
   const item=items[i];
   if(a==='Edit'){
     const next=prompt('Edit claim',item.claim);
     if(next?.trim()){
       const r=await fetch(`${API}/api/data/evidence/${encodeURIComponent(item.evidence_id)}?validation=review&claim=${encodeURIComponent(next.trim())}`,{method:'PATCH'});
       if(r.ok){setItems(items.map((x,k)=>k===i?{...x,claim:next.trim(),validation:'review'}:x));setMessage(`Edited ${item.evidence_id} and saved it.`)}else setMessage('Could not save the edit.');
     }
     return;
   }
   const nextValidation=a==='Accept'?'pass':'review';
   const r=await fetch(`${API}/api/data/evidence/${encodeURIComponent(item.evidence_id)}?validation=${nextValidation}`,{method:'PATCH'});
   if(r.ok){setItems(items.map((x,k)=>k===i?{...x,validation:nextValidation}:x));setMessage(`${a} applied to ${item.evidence_id} and saved.`)}else setMessage('Could not save the review action.');
 };
 return <div><div className="page-head"><div><div className="eyebrow">Evidence review</div><h1>Claims, sources and validation.</h1><p>{meta?.total?.toLocaleString()||'Large'} records · filter the connected research dataset before use.</p></div></div>
 <div className="filter-bar"><input value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}} placeholder="Search claims, entities or excerpts…"/><select value={market} onChange={e=>{setMarket(e.target.value);setPage(1)}}>{filters.markets?.map((x:string)=><option key={x}>{x}</option>)}</select><select value={topic} onChange={e=>{setTopic(e.target.value);setPage(1)}}>{filters.topics?.map((x:string)=><option key={x}>{x}</option>)}</select><select value={validation} onChange={e=>{setValidation(e.target.value);setPage(1)}}>{filters.statuses?.map((x:string)=><option key={x}>{x}</option>)}</select></div>
 {message&&<div className="success-box"><CheckCircle2 size={17}/>{message}<button onClick={()=>setMessage('')}><X size={15}/></button></div>}
 <div className="dataset-note">{meta?.total?.toLocaleString()||'…'} matching evidence records. Data source is controlled by the backend configuration.</div>
 <div className="evidence-list">{items.map((x,i)=><div className="evidence-row" key={x.evidence_id}><div className="evidence-num">{String((page-1)*12+i+1).padStart(2,'0')}</div><div className="evidence-main"><div className="evidence-title"><h3>{x.claim}</h3><span className={`status ${x.validation==='pass'?'completed':'failed'}`}>{x.validation==='pass'?'Validated':'Review'}</span></div><p>{x.market} · {x.entity} · {x.topic} · {x.date} · {x.source_id}</p><p className="evidence-excerpt">{x.excerpt}</p><div className="confidence"><span>Confidence</span><div><i style={{width:`${Number(x.confidence)*100}%`}}/></div><b>{Math.round(Number(x.confidence)*100)}%</b></div><div className="evidence-actions">{['Accept','Edit','Reject','Request deeper research'].map(a=><button key={a} onClick={()=>act(i,a)}>{a}</button>)}</div></div></div>)}</div>
 <div className="pagination"><button disabled={page<=1} onClick={()=>setPage(page-1)}>Previous</button><span>Page {meta?.page||page} of {meta?.pages||'…'}</span><button disabled={page>=(meta?.pages||1)} onClick={()=>setPage(page+1)}>Next</button></div></div>
}
function ReportChart({chart}:{chart:any}){
 const data=(chart?.data||[]).filter((d:any)=>Number.isFinite(Number(d?.value)));
 if(!data.length)return null;
 const type=chart.chart_type||'bar';
 const width=720,height=250,pad={l:46,r:22,t:24,b:52};
 const max=Math.max(...data.map((d:any)=>Number(d.value)),1);
 const min=Math.min(0,...data.map((d:any)=>Number(d.value)));
 const range=Math.max(max-min,1);
 const x=(i:number)=>pad.l+i*((width-pad.l-pad.r)/Math.max(data.length-1,1));
 const y=(v:number)=>pad.t+(max-v)/range*(height-pad.t-pad.b);
 if(type==='donut'){
   const total=data.reduce((a:any,d:any)=>a+Number(d.value),0)||1; let cursor=0; const cx=width/2,cy=118,r=72,inner=43;
   return <div className="exhibit-chart"><div className="donut-wrap"><svg viewBox={`0 0 ${width} ${height}`} role="img" aria-label={chart.title}>
     {data.map((d:any,i:number)=>{const share=Number(d.value)/total;const a0=cursor*Math.PI*2-Math.PI/2;cursor+=share;const a1=cursor*Math.PI*2-Math.PI/2;const large=share>.5?1:0;const p1=[cx+r*Math.cos(a0),cy+r*Math.sin(a0)],p2=[cx+r*Math.cos(a1),cy+r*Math.sin(a1)],q1=[cx+inner*Math.cos(a1),cy+inner*Math.sin(a1)],q2=[cx+inner*Math.cos(a0),cy+inner*Math.sin(a0)];return <path key={i} d={`M ${p1[0]} ${p1[1]} A ${r} ${r} 0 ${large} 1 ${p2[0]} ${p2[1]} L ${q1[0]} ${q1[1]} A ${inner} ${inner} 0 ${large} 0 ${q2[0]} ${q2[1]} Z`} className="donut-segment"/>})}
     <circle cx={cx} cy={cy} r={inner-1} className="donut-hole"/><text x={cx} y={cy-2} textAnchor="middle" className="donut-total">{chart.unit?`${total}${chart.unit}`:total}</text><text x={cx} y={cy+16} textAnchor="middle" className="donut-caption">total</text>
   </svg></div><div className="chart-legend">{data.map((d:any,i:number)=><div key={i}><span className="legend-dot" style={{'--i':i} as any}/><span>{d.label}</span><b>{d.value}{chart.unit}</b></div>)}</div></div>
 }
 if(type==='line'){
   const pts=data.map((d:any,i:number)=>`${x(i)},${y(Number(d.value))}`).join(' ');
   return <svg viewBox={`0 0 ${width} ${height}`} role="img" aria-label={chart.title} className="report-svg"><line x1={pad.l} x2={width-pad.r} y1={y(0)} y2={y(0)} className="chart-axis"/><polyline points={pts} className="chart-line" fill="none"/>{data.map((d:any,i:number)=><g key={i}><circle cx={x(i)} cy={y(Number(d.value))} r="4" className="chart-point"/><text x={x(i)} y={height-20} textAnchor="middle" className="chart-label">{d.label}</text><text x={x(i)} y={y(Number(d.value))-10} textAnchor="middle" className="chart-value">{d.value}{chart.unit}</text></g>)}</svg>
 }
 const barW=Math.min(72,(width-pad.l-pad.r)/Math.max(data.length,1)-18);
 return <svg viewBox={`0 0 ${width} ${height}`} role="img" aria-label={chart.title} className="report-svg"><line x1={pad.l} x2={width-pad.r} y1={y(0)} y2={y(0)} className="chart-axis"/>{data.map((d:any,i:number)=>{const bw=width-pad.l-pad.r;const cx=pad.l+(i+.5)*(bw/data.length);const yy=y(Number(d.value));return <g key={i}><rect x={cx-barW/2} y={yy} width={barW} height={Math.max(2,y(0)-yy)} rx="3" className="chart-bar"/><text x={cx} y={height-20} textAnchor="middle" className="chart-label">{d.label}</text><text x={cx} y={yy-9} textAnchor="middle" className="chart-value">{d.value}{chart.unit}</text></g>})}</svg>
}

function ReportView({job,data}:{job?:any;data?:DatasetOverview|null}){
 const report=job?.report;
 const fallback={title:'Research report workspace',subtitle:'Run a research job to generate an evidence-backed strategy report.',report_date:'',executive_summary:'Your generated report will follow a structured executive format with quantitative exhibits where the validated evidence supports them.',at_a_glance:[],key_findings:[],market_signals:[],competitor_observations:[],implications:[],strategic_directions:[],executive_actions:[],exhibits:[],limitations:[]};
 const dynamicFallback={...fallback,at_a_glance:[{label:'Research requests',value:(data?.requests||0).toLocaleString(),context:'Expanded demo dataset'},{label:'Sources',value:(data?.sources||0).toLocaleString(),context:'Indexed source records'},{label:'Validated evidence',value:(data?.validated_evidence||0).toLocaleString(),context:'Pass-validated records'},{label:'Average confidence',value:`${data?.avg_confidence||0}%`,context:'Across evidence records'}],key_findings:[`The dataset contains ${(data?.validated_evidence||0).toLocaleString()} validated evidence records.`,`The current portfolio spans ${(data?.top_topics?.length||0)} recurring research themes.`,`Evidence volume is tracked across ${(data?.evidence_by_year?.length||0)} annual periods.`],exhibits:[{type:'line',title:'Evidence volume by year',subtitle:'Synthetic demo dataset trend',data:(data?.evidence_by_year||[]).map((x:any)=>({label:x.year,value:x.value})),unit:'',source_note:'Expanded synthetic demo dataset'}]};
 const r=report||dynamicFallback;
 const section=(title:string,items:any[])=>items?.length?<section className="report-section"><div className="section-kicker">{title}</div><ul>{items.map((x:any,i:number)=><li key={i}>{x}</li>)}</ul></section>:null;
 return <div className="report-workspace"><div className="report-top"><div><div className="eyebrow">Strategy brief builder</div><h1>{r.title}</h1><p>{r.subtitle}</p></div><div className="report-meta-actions"><span className="report-status">{report?'Evidence-backed draft':'Awaiting research'}</span><button className="outline-btn" onClick={()=>window.print()}><FileText size={16}/> Print / PDF</button></div></div>
   <article className="strategy-report">
    <div className="report-coverline"><span>McKINSEY & COMPANY · AI MARKET RESEARCH & STRATEGY ENGINE</span><span>{r.report_date}</span></div>
    <div className="report-title-block"><div className="eyebrow">Executive research report</div><h2>{r.title}</h2><p>{r.subtitle}</p></div>
    {r.at_a_glance?.length>0&&<section className="glance-section"><div className="section-kicker">At a glance</div><div className="glance-grid">{r.at_a_glance.map((m:any,i:number)=><div className="glance-card" key={i}><small>{m.label}</small><strong>{m.value}</strong><span>{m.context}</span></div>)}</div></section>}
    <section className="interpretation-block"><div className="section-kicker">Executive interpretation</div><p>{r.executive_summary}</p></section>
    {section('Key findings',r.key_findings)}
    {section('Market signals',r.market_signals)}
    {section('Competitor observations',r.competitor_observations)}
    {r.exhibits?.length>0&&<section className="exhibits-section"><div className="section-kicker">Exhibits</div>{r.exhibits.map((c:any,i:number)=><div className="exhibit" key={i}><div className="exhibit-head"><div><h3>Exhibit {i+1} · {c.title}</h3><p>{c.subtitle}</p></div></div><ReportChart chart={c}/><div className="source-note">Source: {c.source_note}</div></div>)}</section>}
    {section('Implications',r.implications)}
    {section('Strategic directions',r.strategic_directions)}
    {section('What this means for executives',r.executive_actions)}
    {section('Limitations and human review',r.limitations)}
    {r.citations?.length>0&&<section className="evidence-appendix"><div className="section-kicker">Evidence appendix</div>{r.citations.map((x:string,i:number)=><a className="source-link" href={x} target="_blank" rel="noreferrer" key={i}>{i+1}. {x}</a>)}</section>}
   </article>
 </div>
}

function MemoryView({setView}:{setView:(v:string)=>void}){const [market,setMarket]=useState('All');const [filters,setFilters]=useState<any>({markets:['All']});const [data,setData]=useState<any>(null);useEffect(()=>{fetch(`${API}/api/data/filters`).then(r=>r.json()).then(setFilters).catch(()=>{})},[]);useEffect(()=>{fetch(`${API}/api/data/knowledge?market=${encodeURIComponent(market)}`).then(r=>r.json()).then(setData).catch(()=>{})},[market]);return <div><div className="page-head"><div><div className="eyebrow">Knowledge & memory</div><h1>Research that compounds.</h1><p>Validated findings and recurring patterns calculated from the expanded evidence dataset.</p></div><select className="page-filter" value={market} onChange={e=>setMarket(e.target.value)}>{filters.markets?.map((x:string)=><option key={x}>{x}</option>)}</select></div><div className="memory-grid"><div className="memory-card"><span className="memory-icon"><CheckCircle2/></span><h3>Validated findings</h3><strong className="memory-number">{data?.validated_findings?.toLocaleString()||'…'}</strong><p>Pass-validated evidence available for reuse.</p><button onClick={()=>setView('Sources & Library')}>Explore evidence <ChevronRight size={15}/></button></div><div className="memory-card"><span className="memory-icon"><BrainCircuit/></span><h3>Recurring sector patterns</h3><strong className="memory-number">{data?.topic_patterns?.length||0}</strong><p>Topics with repeated evidence across research requests.</p><button onClick={()=>setView('Sources & Library')}>Review patterns <ChevronRight size={15}/></button></div><div className="memory-card"><span className="memory-icon"><Database/></span><h3>Tracked entities</h3><strong className="memory-number">{data?.entities?.length||0}</strong><p>Companies and entities represented in validated evidence.</p><button onClick={()=>setView('Sources & Library')}>Open evidence <ChevronRight size={15}/></button></div></div><div className="data-chart-grid"><DynamicBars title="Recurring evidence themes" data={(data?.topic_patterns||[]).slice(0,8).map((x:any)=>({label:x.topic,value:x.count}))} xKey="label" yKey="value"/><DynamicBars title="Most observed entities" data={(data?.entities||[]).slice(0,8).map((x:any)=>({label:x.entity,value:x.count}))} xKey="label" yKey="value"/></div></div>}
function OpsView(){return <div><div className="page-head"><div><div className="eyebrow">Operations & quality</div><h1>Research system health.</h1><p>Monitor duration, source coverage, validation outcomes and cost controls.</p></div></div><div className="ops-grid">{[['Avg research time','2h 18m'],['Source coverage','92%'],['Validation failure','6.4%'],['Reviewer feedback','4.6/5']].map(x=><div className="metric-card" key={x[0]}><span>{x[0]}</span><strong>{x[1]}</strong><small>Current operating signal</small><MiniLine variant={0}/></div>)}</div><div className="cost-panel"><div><div className="eyebrow light">Cost optimization</div><h2>Control spend without weakening reliability.</h2></div><div className="cost-items">{['Caching','Request batching','Tiered model routing','Token-budget controls','Scheduled data refreshes','Usage monitoring & cost alerts'].map(x=><div key={x}><ShieldCheck size={17}/><b>{x}</b></div>)}</div></div></div>}

function ProfileView({account}:{account:Account}){const initials=account.name.split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase();return <div><div className="page-head"><div><div className="eyebrow">User profile</div><h1>Your research identity.</h1><p>Your account information is used across the workspace profile and settings.</p></div></div><div className="account-layout"><section className="account-card profile-card-large"><div className="big-avatar">{initials}</div><div><h2>{account.name}</h2><p>@{account.userId}</p><span className="account-role">{account.role}</span></div></section><section className="account-card"><div className="account-section-head"><h3>Account information</h3><span className="status completed">Saved</span></div><div className="account-fields"><div><small>Full name</small><strong>{account.name}</strong></div><div><small>User ID</small><strong>{account.userId}</strong></div><div><small>Email</small><strong>{account.email}</strong></div><div><small>Role</small><strong>{account.role}</strong></div></div></section></div></div>}
function SettingsView({account,setAccount,theme,changeTheme,signOut}:{account:Account;setAccount:(a:Account)=>void;theme:'light'|'dark';changeTheme:(t:'light'|'dark')=>void;signOut:()=>void}){
 const [name,setName]=useState(account.name);const [email,setEmail]=useState(account.email);const [saved,setSaved]=useState(false);const [error,setError]=useState('');
 const save=async()=>{setError('');try{const token=localStorage.getItem(SESSION_KEY);const r=await fetch(`${API}/api/auth/profile`,{method:'PATCH',headers:{'Content-Type':'application/json',...apiHeaders(token||undefined)},body:JSON.stringify({full_name:name.trim()||account.name,email:email.trim()||account.email})});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.detail||'Could not save changes.');setAccount(j.user);setSaved(true);setTimeout(()=>setSaved(false),1800)}catch(e:any){setError(e?.message||'Could not save changes.')}}
 return <div><div className="page-head"><div><div className="eyebrow">Workspace settings</div><h1>Manage your account.</h1><p>Update profile details and choose how the research workspace looks.</p></div></div><div className="settings-layout"><section className="settings-card"><div className="settings-title"><UserRound size={18}/><div><h3>Profile details</h3><p>These details are stored centrally for cross-device access.</p></div></div><label>Full name<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Email address<input type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>User ID<input value={account.userId} disabled/></label>{error&&<div className="auth-error">{error}</div>}<div className="settings-actions"><button className="primary-settings" onClick={save}><Save size={16}/> {saved?'Saved':'Save changes'}</button></div></section><section className="settings-card"><div className="settings-title"><Sun size={18}/><div><h3>Appearance</h3><p>Choose the interface theme for your workspace.</p></div></div><div className="theme-options"><button className={theme==='light'?'selected':''} onClick={()=>changeTheme('light')}><Sun size={20}/><div><strong>Light</strong><small>Clean and bright</small></div>{theme==='light'&&<CheckCircle2 size={17}/>}</button><button className={theme==='dark'?'selected':''} onClick={()=>changeTheme('dark')}><Moon size={20}/><div><strong>Dark</strong><small>Low-light focused</small></div>{theme==='dark'&&<CheckCircle2 size={17}/>}</button></div></section><section className="settings-card danger-card"><div className="settings-title"><LockKeyhole size={18}/><div><h3>Session</h3><p>Sign out of this browser and return to the login screen.</p></div></div><button className="signout-btn" onClick={signOut}><LogOut size={16}/> Sign out</button></section></div></div>
}

